version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./scripts:/opt/scripts
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped


  pgmigrate:
    image: e11it/pgmigrate:latest
    environment:
      PGHOST: postgres
      PGUSER: pgmigrate
      PGPASSWORD: 1234
    volumes:
      - ./migrations:/opt/migrations
      - ./scripts:/opt/scripts
    networks:
      - postgres
    command: ["/bin/bash","/opt/scripts/do_migrate.sh"]

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
